### PR TITLE
Revert "Temporarily remove test with windows-latest, emacs snapshot"

### PR DESCRIPTION
**Pull request by 10sr**
Reverts editorconfig/editorconfig-emacs#313

### CODE REVIEW

**Comment by jcs090218** [comment]
We should revert this since it defeats the purpose of having the `experimental` flag set up. 🤔 Or else we could just not test the snapshot completely?

**Comment by jcs090218** [comment]
> Umm... I think currently the experimental flag is not so good, because for now this test always marks commits as ❌ and it hides the "actual" status of the commits.

The idea of the `experimental` flag is to make the badge green but keep the status of the job remains the same ❌.

> Before merging this pr I want to find a way to avoid this, or fix the failure of windows-latest-snapshot check...

There are errors from the Emacs snapshot (windows) and not from this package.

**Comment by 10sr** [comment]
👌

**Comment by jcs090218** [comment]
Thanks for taking care of this! :D

**Pull request merged**
