### PR TITLE
Add Github Actions CI

### PR DESCRIPTION
**Pull request by 10sr**

### CODE REVIEW

**Comment by xuhdev** [comment]
Are there any advantages that we would want to do this? I'm good with either way. If it would cost too much time, I'm good with keeping things at travis.

**Comment by 10sr** [comment]
Yeah, I agree with you that it is totally OK to continue using travis! (github actions seems to work a bit faster, but it is not a critical thing) 🙆 
I'm trying this mostly because of a personal interest, it is very strange that tests fail on github actions...

**Comment by 10sr** [comment]
👌

**Comment by xuhdev** [comment]
Oops, seems like traivs.org is going down at the end of this year: https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom?e=[UNIQID] Sorry I didn't notice that they are going to close down so soon!

Do you wanna come back to this PR? Other options include gitlab CI (which is open source), CircleCI, or whatever you want.

**Comment by xuhdev** [comment]
Thanks for the migration!

**Pull request merged**
