### PR TITLE
Adjust shift width for Evil mode

### PR DESCRIPTION
**Pull request by jupl**
#26

### CODE REVIEW

**Comment by trishume** [comment]
:+1:

**Comment by xuhdev** [comment]
I think this part should be added easily like [line 69](https://github.com/editorconfig/editorconfig-emacs/blob/master/editorconfig.el#L69). Do you have any reason to set it in a different place?

**Comment by jupl** [comment]
I tried that first and it didn't work. It's a global mode. The way I put it in the PR did work properly.

**Comment by xuhdev** [comment]
Alright.. I think as long as you can add an if clause to set the shift width only if evil-mode is enabled, it should be fine

**Comment by jupl** [comment]
Updated.

**Comment by xuhdev** [comment]
Thanks!

**Pull request merged**
